
services:
  # PostgreSQL база данных
  db_service:
    image: postgres:16
    env_file: .env
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  # Приложение бот
  backend_service:
    build:
      context: .
    env_file: .env
    depends_on:
      - db_service
    command: ["bash", "-c", "sleep 5 && bash init_migration_scripts.sh && python bot_sushi.py"]
    ports:
      - "8443:8443"

volumes:
  db_data:
